# Generated by Django 4.2.1 on 2023-05-19 14:21

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100)),
                ('Address1', models.CharField(blank=True, max_length=100)),
                ('Address2', models.CharField(blank=True, max_length=100)),
                ('Address3', models.CharField(blank=True, max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Website', models.URLField(blank=True)),
                ('Logo', models.ImageField(max_length=255, upload_to='')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Enquirysource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enquirysourcename', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Enquiry Sources',
            },
        ),
        migrations.CreateModel(
            name='FollowUpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followupstatusname', models.CharField(max_length=255, unique=True)),
                ('followupstatus', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Follow up statuses',
            },
        ),
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Value', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Master Data',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualificationname', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Qualifications',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Syllabus_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Syllabus',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.state')),
            ],
            options={
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=255)),
                ('Branch_code', models.CharField(max_length=255)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Street', models.CharField(blank=True, max_length=100)),
                ('Pincode', models.CharField(blank=True, max_length=50)),
                ('Mobile', models.CharField(max_length=255)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=False)),
                ('District', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='State', chained_model_field='State_name', on_delete=django.db.models.deletion.CASCADE, to='courseapp.district')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.state')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('closed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('Course', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='courseapp.course')),
            ],
            options={
                'verbose_name_plural': 'Batch',
            },
        ),
    ]
