# Generated by Django 4.2.1 on 2023-06-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_alter_course_options_remove_batch_course_batch_batch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Master',
        ),
    ]
