# Generated by Django 4.2.1 on 2023-05-19 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enquiry_Source', models.CharField(choices=[('facebook', 'facebook'), ('indeed', 'indeed'), ('youtube', 'youtube'), ('instagram', 'instagram')], max_length=20, verbose_name='Enquiry Source')),
                ('Phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('Student', models.CharField(max_length=10, null=True, verbose_name='Student')),
                ('Gender', models.CharField(max_length=10, null=True, verbose_name='Gender')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Alternative_email', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alternative Email')),
                ('Address', models.CharField(blank=True, max_length=10, null=True, verbose_name='Address')),
                ('Alternative_Address', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alternative Address')),
                ('Dob', models.DateField(max_length=10, null=True, verbose_name='Dob')),
                ('Mobile', models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobile')),
                ('Street', models.CharField(blank=True, max_length=10, null=True, verbose_name='Street')),
                ('City', models.CharField(blank=True, max_length=10, null=True, verbose_name='City')),
                ('Pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pincode')),
                ('Whatsapp', models.CharField(max_length=10, null=True, verbose_name='Whatsapp')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
