# Generated by Django 4.2.1 on 2023-05-23 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseapp', '0002_alter_course_options_remove_batch_course_batch_batch_and_more'),
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Collegename',
            field=models.CharField(max_length=10, null=True, verbose_name='College Name'),
        ),
        migrations.AddField(
            model_name='students',
            name='Comments',
            field=models.CharField(max_length=10, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='students',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseapp.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='students',
            name='District',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='State', chained_model_field='State_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='courseapp.district'),
        ),
        migrations.AddField(
            model_name='students',
            name='Qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseapp.qualification', verbose_name='Qualification'),
        ),
        migrations.AddField(
            model_name='students',
            name='Register',
            field=models.CharField(max_length=10, null=True, verbose_name='Registration No'),
        ),
        migrations.AddField(
            model_name='students',
            name='Rollno',
            field=models.CharField(max_length=10, null=True, verbose_name='Roll No'),
        ),
        migrations.AddField(
            model_name='students',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseapp.state'),
        ),
        migrations.AddField(
            model_name='students',
            name='Studentcallstatus',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Student Call Status'),
        ),
        migrations.AddField(
            model_name='students',
            name='nextdate',
            field=models.DateField(null=True, verbose_name='Next Follow-up Date'),
        ),
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='students',
            name='tostaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='To Staff'),
        ),
        migrations.AddField(
            model_name='students',
            name='year',
            field=models.PositiveIntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], null=True, verbose_name='Year of Pass'),
        ),
    ]
