# Generated by Django 4.2.1 on 2023-05-24 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_students_collegename_students_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Phone',
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')], verbose_name='Phone'),
        ),
    ]
